# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8cf2cf3b9835fead68331452f982815e9840c2ac748ca81efc24e0b6253fdd8ca14b04d8498de5e47411e0ff42d27cd3d792dcd0ebedc8ab01d7aea35e1ea228

test:
  secret_key_base: 15efa311336c7f0c28d3b7afd4460b5e40c4edebc0c5728f90239f24f1410b3ba75002bb3d9b3c76e37f711a1ec5d4a1da7d1351962ce313537fb252fed1986d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
